/**
 * Object storage abstraction (FR-AST-001). Two drivers:
 *  - `local`: filesystem (dev / e2e / single node). Uploads are proxied through
 *    the app (`PUT /api/assets/:id/content`) so the server controls limits.
 *  - `s3`: any S3-compatible service (AWS S3, MinIO, R2). Uploads go straight to
 *    the bucket through a short-lived presigned PUT URL.
 * The service always re-reads the stored bytes and validates them (magic bytes,
 * size, dimensions) before an asset becomes `ready`.
 */
export interface PresignedUpload {
  readonly method: "PUT";
  readonly url: string;
  readonly headers: Readonly<Record<string, string>>;
}

export interface StorageDriver {
  readonly kind: "local" | "s3";
  /** Direct-to-storage upload target, or `null` when uploads must go through the app. */
  presignPut(key: string, mime: string, bytes: number): Promise<PresignedUpload | null>;
  put(key: string, data: Uint8Array, mime: string): Promise<void>;
  /** Reads at most `maxBytes + 1` bytes so oversize objects are detectable cheaply. */
  read(key: string, maxBytes: number): Promise<Uint8Array | null>;
  remove(key: string): Promise<void>;
}

/** Storage keys are generated by the server; this guards against traversal anyway. */
export const STORAGE_KEY_PATTERN = /^[a-z0-9][a-z0-9/_.-]{0,250}$/;

export function assertSafeKey(key: string): void {
  if (!STORAGE_KEY_PATTERN.test(key) || key.includes("..") || key.includes("//")) {
    throw new Error("Unsafe storage key");
  }
}
